AI = input ('Which is The Best AI')
Name = input("what is your name?")
Profession = input("What is your profession")
print ("hmm, you are a student")
Age = input("By the way, what is your age?")
print ("oh great")
print ("So, you are")
print (Name)
print ("and you like")
print (AI)